services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: python-app
    command: /app/server_start.dev.sh
    depends_on:
      - app-database
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: app-database
      DB_USER: appuser
      DB_PASSWORD: apppassword
      DB_NAME: postgres

  app-database:
    image: postgres:16
    container_name: app-database
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

