name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  super-linter:
    name: Shell/Docker/YAML/Spell Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: github/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
