name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Ruff Lint (errors)
        run: |
          ruff check . --output-format=github

      - name: Ruff Format (enforce style)
        run: |
          ruff format . --check

